### ISSUE TITLE
REST Search API or Streaming API?

### ISSUE THREAD

**Issue by BShadid** [BShadid/twitterRNN#2]
Our program takes a keyword entry from the user and then curls the twitter page corresponding to a search of that word. There are two ways we can go about doing this:

The first is to use the [REST Search API endpoint](https://dev.twitter.com/rest/public/search), which (I think) works the same way that the search bar on twitter's main website does. This would fetch tweets from the last 7 days containing an *incomplete* list of tweets containing that keyword. This list is incomplete because some users' tweets might be ignored in the search for some reason.

The second is to use the [Streaming API endpoint](https://dev.twitter.com/streaming/overview), which would guarantee a *complete* list of tweets. This might actually be more suitable for what we're trying to implement, but I'm not entirely sure what a complete list includes that an incomplete one filters out or *why* it filters out the tweets that it does. 

Read about both of these, and let's discuss our options.

**Comment by baronbird** [comment]
Two things I noticed going through the docs you linked:

- It looks like the Streaming API provides tweets "as they happen", which means in order to collect tweets, we would have to keep the connection open for a given period of time, say ten seconds. That would make it very difficult to run this program interactively, because every time we wanted to access tweets we would have to wait ten seconds to collect tweets.

- We probably want to filter tweets somehow (at the very least by language so that we don't end up with non-English tweets), and for this the REST Search API would probably be best.

With that in mind, the REST API looks like our best bet.
